package com.backend.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;

import com.backend.model.User;
import com.backend.repository.UserRepository;


@CrossOrigin(origins = "http://localhost:5173")
@RestController
@RequestMapping("/api/users")
public class UserController {

    @Autowired
    private UserRepository userRepository;

    @PostMapping("/signup")
    public String signup(@RequestBody User user) {
        if (userRepository.existsByEmail(user.getEmail())) {
            return "Email already exists";
        }
        if (userRepository.existsByUsername(user.getUsername())) {
            return "Username already exists";
        }
        userRepository.save(user);
        return "User registered successfully";
    }

//    @PostMapping("/signup")
//    public String signup(@RequestBody User user) {
//        return "fail"; // RED phase: this makes the tests fail
//    }

    @PostMapping("/login")
    public ResponseEntity<String> login(@RequestBody User loginUser) {
        User user = userRepository.findByEmail(loginUser.getEmail());
        if (user == null) {
            return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body("User not found");
        }
        if (!user.getPassword().equals(loginUser.getPassword())) {
            return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body("Incorrect password");
        }
        return ResponseEntity.ok("Login successful");
    }

//    @PostMapping("/login")
//    public ResponseEntity<String> login(@RequestBody User loginUser) {
//        return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body("Always fails"); // intentional bug
//    }

}
